### ISSUE TITLE
Remove Avalonia dependency

### ISSUE THREAD

**Issue by DrWenz** [AvaloniaInside/SplashScreen#1]
https://github.com/AvaloniaInside/SplashScreen/blob/a0afa28a47a88624696c9333a8998ebe12aae00e/src/AvaloniaInside.SplashScreen.csproj#L24

@OmidID I think we can safely remove the Avalonia dependency or?

**Comment by OmidID** [comment]
Yes. you right. we only need Linux framebuffer dependency

**Comment by DrWenz** [comment]
> Yes. you right. we only need Linux framebuffer dependency

ok i will remove it 👍🏽
