### ISSUE TITLE
SkiaSharp.NativeAssets.Linux dependency

### ISSUE THREAD

**Issue by DrWenz** [AvaloniaInside/SplashScreen#2]
https://github.com/AvaloniaInside/SplashScreen/blob/a0afa28a47a88624696c9333a8998ebe12aae00e/src/AvaloniaInside.SplashScreen.csproj#L27

On testing I faced some issue with SkiaSharp.NativeAssets.Linux.NoDependencies.
I got the error: `Unable to find an entry point named 'skottie_animation_make_from_data' in shared library libSkiaSharp`
After adding `SkiaSharp.NativeAssets.Linux` to my demo app, it works.
I run on Yocto Reference Image from Toradex.
What's your suggestion @OmidID ?

**Comment by OmidID** [comment]
SkiaSharp has a dependency on fontconfig that I already added to the image. we can safely use normal skiasharp for linux

**Comment by DrWenz** [comment]
> SkiaSharp has a dependency on fontconfig that I already added to the image. we can safely use normal skiasharp for linux

ok perfect, I will change it 👍🏽
